In [51]:
import importlib
import fetch_data as td
import model as mod

In [75]:
# Après avoir modifié le fichier .py :
importlib.reload(mod)

In [2]:
ids = td.get_movie_ids_list(td.headers, 50, ending_date="03-18-2026", ascending=False)
historic_df = td.get_movies_info(ids, td.headers)
df_cleaned = td.clean_data(historic_df)
df_cleaned.head()

getting movie ids

  0%|          | 0/50 [00:00<?, ?it/s]

100%|██████████| 50/50 [00:05<00:00,  8.41it/s]

getting movie info

100%|██████████| 1000/1000 [03:47<00:00,  4.39it/s]

,belongs_to_collection,budget,id,origin_country,overview,popularity,release_date,revenue,runtime,title,vote_average,vote_count,main_genre_id,main_genre_name,full_poster_path,overview_count,title_count,timestamp
0,NaN,150000000,1327819,US,Scientists have discovered how to 'hop' human ...,137.5015,2026-03-04,164700900,105,Hoppers,7.735,215,16,Animation,https://image.tmdb.org/t/p/original//xjtWQ2CL1...,296,7,1772582400
1,NaN,80000000,1159831,US,A lonely Frankenstein travels to 1930s Chicago...,36.0001,2026-03-04,21000000,126,The Bride!,6.282,172,878,Science Fiction,https://image.tmdb.org/t/p/original//lV8YHwGkY...,242,10,1772582400
2,NaN,45000000,1159559,US,When a new Ghostface killer emerges in the qui...,130.1839,2026-02-25,177977863,114,Scream 7,5.900,349,27,Horror,https://image.tmdb.org/t/p/original//jjyuk0edL...,293,8,1771977600
3,NaN,0,799882,US,When her tranquil life on a remote island is s...,173.2240,2026-02-17,0,102,The Bluff,6.313,283,28,Action,https://image.tmdb.org/t/p/original//w0jwjFmRu...,223,9,1771286400
4,NaN,20000000,1119449,US,A 'Man from the Future' arrives at an LA diner...,78.6582,2026-02-13,8705352,135,"Good Luck, Have Fun, Don't Die",6.900,182,878,Science Fiction,https://image.tmdb.org/t/p/original//rWcfOdY7T...,227,30,1770940800

In [3]:
df_train = df_cleaned[df_cleaned['revenue']>0]
y = df_train['revenue']

In [4]:
pipeline = mod.create_random_forest_pipeline()
scores = mod.model_cross_validation(df_train, pipeline)

In [5]:
print("Moyenne du revenue    :", y.mean())
print("Écart-type du revenue :", y.std())
print("Médiane du revenue    :", y.median())

# RMSE relatif (coefficient de variation)
rmse_moyen = - scores.mean()
print("RMSE :", rmse_moyen)
print("RMSE relatif (RMSE / std)  :", rmse_moyen / y.std())
print("RMSE relatif (RMSE / mean) :", rmse_moyen / y.mean())

Moyenne du revenue    : 88684860.26824817
Écart-type du revenue : 221556700.71611667
Médiane du revenue    : 14339357.5
RMSE : 152361845.19540375
RMSE relatif (RMSE / std)  : 0.6876878230400572
RMSE relatif (RMSE / mean) : 1.7180141541019471

In [9]:
param_grid = {
    "n_estimators":       [100],
    "max_depth":          [None],
    "tfidf_max_features": [3000],
    "tfidf_ngram_range":  [(1,1), (1,2), (2,3)],
    "tfidf_min_df":       [2, 5],
}

In [10]:
results = mod.grid_search_random_forest(df_train, param_grid=param_grid)
results

6 combinaisons à tester...

RMSE: 149,929,111 (+/- 72,811,400) | {'n_estimators': 100, 'max_depth': None, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 150,517,516 (+/- 71,832,780) | {'n_estimators': 100, 'max_depth': None, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 148,824,499 (+/- 75,020,628) | {'n_estimators': 100, 'max_depth': None, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 148,269,571 (+/- 74,590,428) | {'n_estimators': 100, 'max_depth': None, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 146,415,088 (+/- 79,385,113) | {'n_estimators': 100, 'max_depth': None, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (2, 3), 'tfidf_min_df': 2}
RMSE: 149,518,541 (+/- 77,878,272) | {'n_estimators': 100, 'max_depth': None, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (2, 3), 'tfidf_min_df': 5}

,n_estimators,max_depth,tfidf_max_features,tfidf_ngram_range,tfidf_min_df,rmse_mean,rmse_std
4,100,None,3000,"(2, 3)",2,1.464151e+08,7.938511e+07
3,100,None,3000,"(1, 2)",5,1.482696e+08,7.459043e+07
2,100,None,3000,"(1, 2)",2,1.488245e+08,7.502063e+07
5,100,None,3000,"(2, 3)",5,1.495185e+08,7.787827e+07
0,100,None,3000,"(1, 1)",2,1.499291e+08,7.281140e+07
1,100,None,3000,"(1, 1)",5,1.505175e+08,7.183278e+07

In [56]:
results = mod.grid_search_elastic_net(df_train)

576 combinaisons à tester...
RMSE: 145,377,964 (+/- 59,770,446) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 145,205,324 (+/- 59,787,858) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 145,021,941 (+/- 59,408,912) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 144,819,931 (+/- 59,606,791) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 144,747,928 (+/- 59,628,939) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 144,792,540 (+/- 59,684,531) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 144,708,611 (+/- 60,744,835) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 145,032,989 (+/- 60,232,086) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 145,021,941 (+/- 59,408,912) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 144,935,148 (+/- 60,639,316) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 145,119,582 (+/- 60,404,160) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 144,792,540 (+/- 59,684,531) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 144,739,525 (+/- 60,875,025) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 145,032,989 (+/- 60,232,086) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 145,021,941 (+/- 59,408,912) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 144,939,707 (+/- 60,828,581) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 145,119,234 (+/- 60,465,299) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 144,792,540 (+/- 59,684,531) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 144,715,595 (+/- 60,894,197) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 145,032,989 (+/- 60,232,086) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 145,021,941 (+/- 59,408,912) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 145,010,942 (+/- 60,957,981) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 145,119,234 (+/- 60,465,299) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 144,792,540 (+/- 59,684,531) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 146,035,355 (+/- 58,946,394) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 145,835,805 (+/- 58,965,403) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 145,706,913 (+/- 58,532,589) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 145,432,840 (+/- 58,722,740) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 145,347,611 (+/- 58,749,886) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 145,418,612 (+/- 58,817,774) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 144,965,837 (+/- 60,120,178) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 145,448,329 (+/- 59,481,297) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 145,706,913 (+/- 58,532,589) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 145,279,926 (+/- 59,992,274) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 145,525,978 (+/- 59,698,546) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 145,418,612 (+/- 58,817,774) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 144,944,952 (+/- 60,285,582) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 145,448,329 (+/- 59,481,297) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 145,706,913 (+/- 58,532,589) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 145,191,429 (+/- 60,233,794) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 145,466,128 (+/- 59,781,013) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 145,418,612 (+/- 58,817,774) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 144,894,373 (+/- 60,312,658) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 145,448,329 (+/- 59,481,297) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 145,706,913 (+/- 58,532,589) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 145,216,442 (+/- 60,400,766) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 145,466,128 (+/- 59,781,013) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 145,418,612 (+/- 58,817,774) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 147,255,620 (+/- 57,814,508) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 147,020,762 (+/- 57,828,978) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 147,007,654 (+/- 57,324,076) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 146,645,305 (+/- 57,482,204) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 146,540,595 (+/- 57,517,148) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 146,654,317 (+/- 57,606,551) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 145,460,862 (+/- 59,286,127) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 146,233,408 (+/- 58,444,141) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 147,007,654 (+/- 57,324,076) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 145,944,808 (+/- 59,123,257) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 146,297,673 (+/- 58,733,431) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 146,654,317 (+/- 57,606,551) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 145,335,554 (+/- 59,507,209) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 146,233,408 (+/- 58,444,141) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 147,007,654 (+/- 57,324,076) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 145,667,520 (+/- 59,445,027) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 146,120,031 (+/- 58,849,158) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 146,654,317 (+/- 57,606,551) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 145,234,030 (+/- 59,548,446) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 146,233,408 (+/- 58,444,141) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 147,007,654 (+/- 57,324,076) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 145,591,994 (+/- 59,673,114) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 146,120,031 (+/- 58,849,158) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 146,654,317 (+/- 57,606,551) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 149,949,786 (+/- 56,055,493) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 149,675,489 (+/- 56,037,299) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 149,960,839 (+/- 55,414,701) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 149,536,136 (+/- 55,475,886) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 149,401,477 (+/- 55,523,329) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 149,590,002 (+/- 55,658,780) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 146,564,050 (+/- 58,036,830) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 147,984,233 (+/- 56,809,454) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 149,960,839 (+/- 55,414,701) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 147,455,588 (+/- 57,810,301) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 148,030,698 (+/- 57,234,818) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 149,590,002 (+/- 55,658,780) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 146,189,224 (+/- 58,360,030) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 147,984,233 (+/- 56,809,454) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 149,960,839 (+/- 55,414,701) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 146,717,689 (+/- 58,273,551) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 147,574,137 (+/- 57,411,234) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 149,590,002 (+/- 55,658,780) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 145,972,628 (+/- 58,431,349) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 147,984,233 (+/- 56,809,454) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 149,960,839 (+/- 55,414,701) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 146,387,430 (+/- 58,618,463) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 147,574,137 (+/- 57,411,234) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 149,590,002 (+/- 55,658,780) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 159,351,845 (+/- 52,252,813) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 159,215,900 (+/- 51,990,172) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 161,102,360 (+/- 50,759,316) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 161,153,921 (+/- 50,572,473) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 161,001,607 (+/- 50,620,818) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 161,393,447 (+/- 50,902,832) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 150,200,568 (+/- 55,552,106) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 153,954,919 (+/- 53,237,006) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 161,102,360 (+/- 50,759,316) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 152,638,846 (+/- 55,148,378) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 153,938,747 (+/- 54,054,391) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 161,393,447 (+/- 50,902,832) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 148,903,980 (+/- 56,155,198) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 153,954,919 (+/- 53,237,006) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 161,102,360 (+/- 50,759,316) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 150,139,008 (+/- 55,983,181) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 152,453,023 (+/- 54,414,624) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 161,393,447 (+/- 50,902,832) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 148,312,879 (+/- 56,320,012) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 153,954,919 (+/- 53,237,006) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 161,102,360 (+/- 50,759,316) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 148,835,207 (+/- 56,673,738) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 152,453,023 (+/- 54,414,624) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 161,393,447 (+/- 50,902,832) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 290,343,211 (+/- 49,989,267) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 292,553,145 (+/- 46,990,425) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 298,327,825 (+/- 34,181,505) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 292,144,387 (+/- 47,126,944) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 291,381,998 (+/- 46,666,981) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 291,229,008 (+/- 49,765,338) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 302,639,664 (+/- 68,458,504) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 302,832,320 (+/- 55,339,978) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 298,327,825 (+/- 34,181,505) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 297,394,599 (+/- 57,675,666) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 289,970,222 (+/- 54,353,407) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 291,229,008 (+/- 49,765,338) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 286,039,999 (+/- 71,808,390) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 302,832,320 (+/- 55,339,978) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 298,327,825 (+/- 34,181,505) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 272,288,919 (+/- 59,892,803) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}

In [81]:
param_grid = {
            "alpha":             [0.01, 0.1, 1.0],
            "l1_ratio":          [0.5, 0.7, 0.9],
            "tfidf_max_features":[5000, 10000],
            "tfidf_ngram_range": [(1,1), (1,2)],
            "tfidf_min_df":      [2, 5, 10, 20, 30],
            "tfidf_max_df":      [0.6, 0.8, 0.9]
        }

In [82]:
results_new = mod.grid_search_elastic_net(df_train, param_grid)

540 combinaisons à tester...
RMSE: 146,919,867 (+/- 59,773,628) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.6}
RMSE: 146,919,867 (+/- 59,773,628) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.8}
RMSE: 146,919,867 (+/- 59,773,628) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.9}
RMSE: 148,003,460 (+/- 58,291,009) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.6}
RMSE: 148,003,460 (+/- 58,291,009) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.8}
RMSE: 148,003,460 (+/- 58,291,009) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.9}
RMSE: 151,414,741 (+/- 57,886,255) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.6}
RMSE: 151,414,741 (+/- 57,886,255) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.8}
RMSE: 151,414,741 (+/- 57,886,255) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.9}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.6}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.8}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.9}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.6}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.8}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.9}
RMSE: 146,642,644 (+/- 59,977,116) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.6}
RMSE: 146,642,644 (+/- 59,977,116) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.8}
RMSE: 146,642,644 (+/- 59,977,116) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.9}
RMSE: 147,748,339 (+/- 58,442,340) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.6}
RMSE: 147,748,339 (+/- 58,442,340) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.8}
RMSE: 147,748,339 (+/- 58,442,340) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.9}
RMSE: 151,306,112 (+/- 57,913,040) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.6}
RMSE: 151,306,112 (+/- 57,913,040) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.8}
RMSE: 151,306,112 (+/- 57,913,040) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.9}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.6}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.8}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.9}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.6}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.8}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.9}
RMSE: 146,919,867 (+/- 59,773,628) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.6}
RMSE: 146,919,867 (+/- 59,773,628) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.8}
RMSE: 146,919,867 (+/- 59,773,628) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.9}
RMSE: 148,003,460 (+/- 58,291,009) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.6}
RMSE: 148,003,460 (+/- 58,291,009) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.8}
RMSE: 148,003,460 (+/- 58,291,009) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.9}
RMSE: 151,414,741 (+/- 57,886,255) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.6}
RMSE: 151,414,741 (+/- 57,886,255) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.8}
RMSE: 151,414,741 (+/- 57,886,255) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.9}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.6}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.8}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.9}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.6}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.8}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.9}
RMSE: 146,642,644 (+/- 59,977,116) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.6}
RMSE: 146,642,644 (+/- 59,977,116) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.8}
RMSE: 146,642,644 (+/- 59,977,116) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.9}
RMSE: 147,748,339 (+/- 58,442,340) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.6}
RMSE: 147,748,339 (+/- 58,442,340) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.8}
RMSE: 147,748,339 (+/- 58,442,340) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.9}
RMSE: 151,306,112 (+/- 57,913,040) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.6}
RMSE: 151,306,112 (+/- 57,913,040) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.8}
RMSE: 151,306,112 (+/- 57,913,040) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.9}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.6}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.8}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.9}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.6}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.8}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.9}
RMSE: 148,775,942 (+/- 58,537,049) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.6}
RMSE: 148,775,942 (+/- 58,537,049) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.8}
RMSE: 148,775,942 (+/- 58,537,049) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.9}
RMSE: 151,630,442 (+/- 56,204,430) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.6}
RMSE: 151,630,442 (+/- 56,204,430) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.8}
RMSE: 151,630,442 (+/- 56,204,430) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.9}
RMSE: 156,459,033 (+/- 55,934,131) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.6}
RMSE: 156,459,033 (+/- 55,934,131) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.8}
RMSE: 156,459,033 (+/- 55,934,131) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.9}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.6}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.8}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.9}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.6}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.8}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.9}
RMSE: 148,290,945 (+/- 58,845,368) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.6}
RMSE: 148,290,945 (+/- 58,845,368) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.8}
RMSE: 148,290,945 (+/- 58,845,368) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.9}
RMSE: 151,263,213 (+/- 56,443,111) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.6}
RMSE: 151,263,213 (+/- 56,443,111) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.8}
RMSE: 151,263,213 (+/- 56,443,111) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.9}
RMSE: 156,342,755 (+/- 55,966,797) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.6}
RMSE: 156,342,755 (+/- 55,966,797) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.8}
RMSE: 156,342,755 (+/- 55,966,797) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.9}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.6}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.8}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.9}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.6}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.8}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.9}
RMSE: 148,775,942 (+/- 58,537,049) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.6}
RMSE: 148,775,942 (+/- 58,537,049) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.8}
RMSE: 148,775,942 (+/- 58,537,049) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.9}
RMSE: 151,630,442 (+/- 56,204,430) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.6}
RMSE: 151,630,442 (+/- 56,204,430) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.8}
RMSE: 151,630,442 (+/- 56,204,430) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.9}
RMSE: 156,459,033 (+/- 55,934,131) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.6}
RMSE: 156,459,033 (+/- 55,934,131) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.8}
RMSE: 156,459,033 (+/- 55,934,131) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.9}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.6}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.8}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.9}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.6}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.8}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.9}
RMSE: 148,290,945 (+/- 58,845,368) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.6}
RMSE: 148,290,945 (+/- 58,845,368) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.8}
RMSE: 148,290,945 (+/- 58,845,368) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.9}
RMSE: 151,263,213 (+/- 56,443,111) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.6}
RMSE: 151,263,213 (+/- 56,443,111) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.8}
RMSE: 151,263,213 (+/- 56,443,111) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.9}
RMSE: 156,342,755 (+/- 55,966,797) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.6}
RMSE: 156,342,755 (+/- 55,966,797) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.8}
RMSE: 156,342,755 (+/- 55,966,797) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.9}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.6}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.8}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.9}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.6}

In [83]:
results_new.sort_values(["rmse_mean"]).head(20)

,alpha,l1_ratio,tfidf_max_features,tfidf_ngram_range,tfidf_min_df,tfidf_max_df,rmse_mean,rmse_std
266,0.1,0.7,5000,"(1, 2)",20,0.9,1.428925e+08,6.302261e+07
264,0.1,0.7,5000,"(1, 2)",20,0.6,1.428925e+08,6.302261e+07
265,0.1,0.7,5000,"(1, 2)",20,0.8,1.428925e+08,6.302261e+07
250,0.1,0.7,5000,"(1, 1)",20,0.8,1.428925e+08,6.302261e+07
251,0.1,0.7,5000,"(1, 1)",20,0.9,1.428925e+08,6.302261e+07
249,0.1,0.7,5000,"(1, 1)",20,0.6,1.428925e+08,6.302261e+07
280,0.1,0.7,10000,"(1, 1)",20,0.8,1.428925e+08,6.302261e+07
279,0.1,0.7,10000,"(1, 1)",20,0.6,1.428925e+08,6.302261e+07
281,0.1,0.7,10000,"(1, 1)",20,0.9,1.428925e+08,6.302261e+07
295,0.1,0.7,10000,"(1, 2)",20,0.8,1.428925e+08,6.302261e+07
296,0.1,0.7,10000,"(1, 2)",20,0.9,1.428925e+08,6.302261e+07
294,0.1,0.7,10000,"(1, 2)",20,0.6,1.428925e+08,6.302261e+07
205,0.1,0.5,5000,"(1, 2)",20,0.8,1.433665e+08,6.457786e+07
234,0.1,0.5,10000,"(1, 2)",20,0.6,1.433665e+08,6.457786e+07
206,0.1,0.5,5000,"(1, 2)",20,0.9,1.433665e+08,6.457786e+07
221,0.1,0.5,10000,"(1, 1)",20,0.9,1.433665e+08,6.457786e+07
220,0.1,0.5,10000,"(1, 1)",20,0.8,1.433665e+08,6.457786e+07
219,0.1,0.5,10000,"(1, 1)",20,0.6,1.433665e+08,6.457786e+07
191,0.1,0.5,5000,"(1, 1)",20,0.9,1.433665e+08,6.457786e+07
189,0.1,0.5,5000,"(1, 1)",20,0.6,1.433665e+08,6.457786e+07