In [18]:
import fetch_data as td

In [19]:
ids= td.get_movie_ids_list(50, headers=td.headers)
df=td.get_movies_info(ids,headers=td.headers)
df=td.clean_data(df)
df

getting movie ids

  0%|          | 0/50 [00:00<?, ?it/s]

100%|██████████| 50/50 [00:10<00:00,  4.69it/s]

getting movie info

100%|██████████| 1000/1000 [04:32<00:00,  3.67it/s]

,belongs_to_collection,budget,id,origin_country,overview,popularity,release_date,revenue,runtime,title,vote_average,vote_count,main_genre_id,main_genre_name,full_poster_path,overview_count,title_count,timestamp
0,NaN,150000000,1327819,[US],Scientists have discovered how to 'hop' human ...,148.4862,2026-03-04,164700900,105,Hoppers,7.718,195,16,Animation,https://image.tmdb.org/t/p/original//xjtWQ2CL1...,296,7,1772582400
1,NaN,80000000,1159831,[US],A lonely Frankenstein travels to 1930s Chicago...,43.5131,2026-03-04,21000000,126,The Bride!,6.274,166,878,Science Fiction,https://image.tmdb.org/t/p/original//lV8YHwGkY...,242,10,1772582400
2,NaN,45000000,1159559,[US],When a new Ghostface killer emerges in the qui...,77.3621,2026-02-25,177112583,114,Scream 7,6.000,320,27,Horror,https://image.tmdb.org/t/p/original//jjyuk0edL...,293,8,1771977600
3,NaN,0,799882,[US],When her tranquil life on a remote island is s...,193.2064,2026-02-17,0,102,The Bluff,6.338,272,28,Action,https://image.tmdb.org/t/p/original//w0jwjFmRu...,223,9,1771286400
4,NaN,20000000,1119449,[US],A 'Man from the Future' arrives at an LA diner...,102.3336,2026-02-13,8705352,134,"Good Luck, Have Fun, Don't Die",6.991,161,878,Science Fiction,https://image.tmdb.org/t/p/original//rWcfOdY7T...,227,30,1770940800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,100000000,695721,[US],64 years before he becomes the tyrannical pres...,7.6147,2023-11-15,337371917,157,The Hunger Games: The Ballad of Songbirds & Sn...,6.986,3413,878,Science Fiction,https://image.tmdb.org/t/p/original//lrkOYL5GB...,186,50,1700006400
996,NaN,175000000,1022796,[US],"Asha, a sharp-witted idealist, makes a wish so...",9.3079,2023-11-13,254997360,95,Wish,6.226,1751,16,Animation,https://image.tmdb.org/t/p/original//nesuSdJak...,377,4,1699833600
997,NaN,0,1113278,"[CA, GB, US]",Winnie's life is less than wonderful one year ...,1.1193,2023-11-10,970781,87,It's a Wonderful Knife,5.080,176,27,Horror,https://image.tmdb.org/t/p/original//bnm5NntrQ...,345,22,1699574400
998,NaN,16000000,1056360,[US],A novelist fed up with the establishment profi...,3.6856,2023-11-10,22483370,117,American Fiction,7.269,1284,35,Comedy,https://image.tmdb.org/t/p/original//57MFWGHar...,192,16,1699574400
999,NaN,0,1024541,[ES],The buried memories of the Spanish Civil War a...,1.4447,2023-11-10,2232542,105,The Teacher Who Promised the Sea,7.700,141,18,Drama,https://image.tmdb.org/t/p/original//sPc3cUblF...,193,32,1699574400

In [20]:
df[df['revenue']>0]

,belongs_to_collection,budget,id,origin_country,overview,popularity,release_date,revenue,runtime,title,vote_average,vote_count,main_genre_id,main_genre_name,full_poster_path,overview_count,title_count,timestamp
0,NaN,150000000,1327819,[US],Scientists have discovered how to 'hop' human ...,148.4862,2026-03-04,164700900,105,Hoppers,7.718,195,16,Animation,https://image.tmdb.org/t/p/original//xjtWQ2CL1...,296,7,1772582400
1,NaN,80000000,1159831,[US],A lonely Frankenstein travels to 1930s Chicago...,43.5131,2026-03-04,21000000,126,The Bride!,6.274,166,878,Science Fiction,https://image.tmdb.org/t/p/original//lV8YHwGkY...,242,10,1772582400
2,NaN,45000000,1159559,[US],When a new Ghostface killer emerges in the qui...,77.3621,2026-02-25,177112583,114,Scream 7,6.000,320,27,Horror,https://image.tmdb.org/t/p/original//jjyuk0edL...,293,8,1771977600
4,NaN,20000000,1119449,[US],A 'Man from the Future' arrives at an LA diner...,102.3336,2026-02-13,8705352,134,"Good Luck, Have Fun, Don't Die",6.991,161,878,Science Fiction,https://image.tmdb.org/t/p/original//rWcfOdY7T...,227,30,1770940800
7,NaN,80000000,1316092,"[GB, US]",Tragedy strikes when Heathcliff falls in love ...,106.4394,2026-02-11,226400000,136,"""Wuthering Heights""",6.400,516,10749,Romance,https://image.tmdb.org/t/p/original//3YBce6dTh...,125,19,1770768000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,100000000,695721,[US],64 years before he becomes the tyrannical pres...,7.6147,2023-11-15,337371917,157,The Hunger Games: The Ballad of Songbirds & Sn...,6.986,3413,878,Science Fiction,https://image.tmdb.org/t/p/original//lrkOYL5GB...,186,50,1700006400
996,NaN,175000000,1022796,[US],"Asha, a sharp-witted idealist, makes a wish so...",9.3079,2023-11-13,254997360,95,Wish,6.226,1751,16,Animation,https://image.tmdb.org/t/p/original//nesuSdJak...,377,4,1699833600
997,NaN,0,1113278,"[CA, GB, US]",Winnie's life is less than wonderful one year ...,1.1193,2023-11-10,970781,87,It's a Wonderful Knife,5.080,176,27,Horror,https://image.tmdb.org/t/p/original//bnm5NntrQ...,345,22,1699574400
998,NaN,16000000,1056360,[US],A novelist fed up with the establishment profi...,3.6856,2023-11-10,22483370,117,American Fiction,7.269,1284,35,Comedy,https://image.tmdb.org/t/p/original//57MFWGHar...,192,16,1699574400
999,NaN,0,1024541,[ES],The buried memories of the Spanish Civil War a...,1.4447,2023-11-10,2232542,105,The Teacher Who Promised the Sea,7.700,141,18,Drama,https://image.tmdb.org/t/p/original//sPc3cUblF...,193,32,1699574400

In [21]:
df1=df[df['revenue']>0]

In [22]:
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestRegressor

# -------------------------
# 1. Features
# -------------------------
target = "revenue"

text_features = ["overview", "title"]
categorical_features = ["main_genre_name"]
numeric_features = ["budget", "popularity", "runtime", "vote_count", "vote_average", "timestamp"]

X = df1[text_features + categorical_features + numeric_features]
y = df1[target]

# -------------------------
# 2. Pipeline texte
# -------------------------
def combine_text(X):
    return (X["overview"].fillna("") + " " + X["title"].fillna(""))

text_pipeline = Pipeline([
    ("combine", FunctionTransformer(combine_text, validate=False)),
    ("tfidf", TfidfVectorizer(max_features=5000))
])

# -------------------------
# 3. Pipeline numérique
# -------------------------
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

# -------------------------
# 4. Pipeline catégoriel
# -------------------------
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

# -------------------------
# 5. Preprocessing global
# -------------------------
preprocessor = ColumnTransformer([
    ("text", text_pipeline, text_features),
    ("num", numeric_pipeline, numeric_features),
    ("cat", categorical_pipeline, categorical_features),
])

# -------------------------
# 6. Pipeline finale
# -------------------------
pipeline = Pipeline([
    ("preprocessing", preprocessor),
    ("model", RandomForestRegressor(n_estimators=100, random_state=42))
])

# -------------------------
# 7. Cross-validation (10 folds)
# -------------------------
scores = cross_val_score(
    pipeline,
    X,
    y,
    cv=10,
    scoring="neg_root_mean_squared_error",
    n_jobs=-1
)

# -------------------------
# 8. Résultats
# -------------------------
rmse_scores = -scores  # car négatif

print("RMSE par fold :", rmse_scores)
print("RMSE moyen :", rmse_scores.mean())
print("RMSE std :", rmse_scores.std())

RMSE par fold : [2.61139346e+08 1.06888034e+08 1.76635831e+08 2.96141393e+08
 9.96276282e+07 4.79782487e+07 1.50085882e+08 1.53031074e+08
 8.70533404e+07 1.31713567e+08]
RMSE moyen : 151029434.372237
RMSE std : 73156309.7469477

In [23]:
import numpy as np

print("Moyenne des notes :", y.mean())
print("Écart-type des notes :", y.std())

Moyenne des notes : 88470155.45818181
Écart-type des notes : 221199058.61822626

In [26]:
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neural_network import MLPRegressor

# -------------------------
# 1. Features
# -------------------------
target = "revenue"
text_features = ["overview", "title"]
categorical_features = ["main_genre_name"]
numeric_features = [ "popularity", "runtime", "vote_count", "vote_average", "timestamp"]

X = df1[text_features + categorical_features + numeric_features]
y = df1[target]
y_log = np.log1p(y)

# -------------------------
# 2. Pipeline texte
# -------------------------
def combine_text(X):
    return (X["overview"].fillna("") + " " + X["title"].fillna(""))

text_pipeline = Pipeline([
    ("combine", FunctionTransformer(combine_text, validate=False)),
    ("tfidf", TfidfVectorizer(max_features=500))  # réduit pour le MLP
])

# -------------------------
# 3. Pipeline numérique
# -------------------------
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

# -------------------------
# 4. Pipeline catégoriel
# -------------------------
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

# -------------------------
# 5. Preprocessing global
# -------------------------
preprocessor = ColumnTransformer([
    ("text", text_pipeline, text_features),
    ("num", numeric_pipeline, numeric_features),
    ("cat", categorical_pipeline, categorical_features),
])

# -------------------------
# 6. Pipeline finale — MLP
# -------------------------
pipeline = Pipeline([
    ("preprocessing", preprocessor),
    ("scaler_final", StandardScaler(with_mean=False)),  # re-normalise la sortie TF-IDF sparse
    ("model", MLPRegressor(
        hidden_layer_sizes=(256, 128, 64),  # 3 couches cachées
        activation="relu",
        solver="adam",
        learning_rate="adaptive",
        max_iter=300,
        early_stopping=True,       # arrêt si pas d'amélioration
        validation_fraction=0.1,
        n_iter_no_change=15,
        random_state=42
    ))
])

# -------------------------
# 7. Cross-validation (10 folds)
# -------------------------
scores = cross_val_score(
    pipeline,
    X,
    y,
    cv=10,
    scoring="neg_root_mean_squared_error",
    n_jobs=-1
)

# -------------------------
# 8. Résultats
# -------------------------
rmse_scores = -scores
print("RMSE par fold :", rmse_scores)
print("RMSE moyen    :", rmse_scores.mean())
print("RMSE std      :", rmse_scores.std())

RMSE par fold : [3.46758791e+08 1.04298509e+08 2.93223322e+08 3.39957232e+08
 2.04649230e+08 1.37705419e+08 2.50624238e+08 2.61897815e+08
 1.50781214e+08 1.37890751e+08]
RMSE moyen    : 222778652.18929967
RMSE std      : 83882831.26544034

In [25]:
import numpy as np

print("Moyenne du revenue    :", y_log.mean())
print("Écart-type du revenue :", y_log.std())
print("Médiane du revenue    :", y_log.median())

# RMSE relatif (coefficient de variation)
rmse_moyen = rmse_scores.mean()
print("RMSE relatif (RMSE / std)  :", rmse_moyen / y_log.std())
print("RMSE relatif (RMSE / mean) :", rmse_moyen / y_log.mean())

Moyenne du revenue    : 16.05116926003631
Écart-type du revenue : 2.9863239544531988
Médiane du revenue    : 16.47301322360711
RMSE relatif (RMSE / std)  : 1.0666606334063002
RMSE relatif (RMSE / mean) : 0.19845247092025559