In [1]:
import importlib
import fetch_data as td
import model as mod

In [2]:
# Après avoir modifié le fichier .py :
importlib.reload(mod)

In [3]:
ids = td.get_movie_ids_list(td.HEADERS, 10, ending_date="03-18-2026", ascending=False)
historic_df = td.get_movies_info(ids, td.HEADERS)
df_cleaned = td.clean_data(historic_df)
df_cleaned.head()

Fetching movie IDs...

100%|██████████| 10/10 [00:00<00:00, 12.23it/s]

Fetching movie details...

100%|██████████| 200/200 [00:31<00:00,  6.34it/s]

,budget,id,origin_country,overview,popularity,release_date,revenue,runtime,title,vote_average,vote_count,belongs_to_collection,main_genre_id,main_genre_name,full_poster_path,title_char_count,overview_char_count,timestamp
0,110000000,1226863,US,Having thwarted Bowser's previous plot to marr...,298.6540,2026-04-01,122100000,98,The Super Mario Galaxy Movie,6.981,157,NaN,12,Adventure,https://image.tmdb.org/t/p/original/eJGWx219Zc...,28,310,1775001600
1,200000000,687163,US,Science teacher Ryland Grace wakes up on a spa...,237.9095,2026-03-15,323427010,157,Project Hail Mary,8.185,957,NaN,878,Science Fiction,https://image.tmdb.org/t/p/original/yihdXomYb5...,17,433,1773532800
2,0,1115544,US,Two gangsters and the woman they love try to s...,349.1562,2026-03-14,0,107,Mike & Nick & Nick & Alice,6.800,149,NaN,35,Comedy,https://image.tmdb.org/t/p/original/7F0jc75HrS...,26,181,1773446400
3,0,1084187,US,A troupe of ballerinas find themselves fightin...,265.0209,2026-03-13,0,90,Pretty Lethal,6.967,198,NaN,28,Action,https://image.tmdb.org/t/p/original/znTPnXCK3l...,13,167,1773360000
4,0,875828,GB,After his estranged son gets embroiled in a Na...,129.9931,2026-03-05,0,112,Peaky Blinders: The Immortal Man,7.292,644,NaN,80,Crime,https://image.tmdb.org/t/p/original/gRMalasZEz...,32,151,1772668800

In [4]:
df_train = df_cleaned[df_cleaned["revenue"] > 0]
y = df_train["revenue"]

In [5]:
pipeline = mod.create_random_forest_pipeline()
scores = mod.model_cross_validation(df_train, pipeline)

In [6]:
print("Moyenne du revenue    :", y.mean())
print("Écart-type du revenue :", y.std())
print("Médiane du revenue    :", y.median())

# RMSE relatif (coefficient de variation)
rmse_moyen = -scores.mean()
print("RMSE :", rmse_moyen)
print("RMSE relatif (RMSE / std)  :", rmse_moyen / y.std())
print("RMSE relatif (RMSE / mean) :", rmse_moyen / y.mean())

Moyenne du revenue    : 95432427.5042735
Écart-type du revenue : 233702218.6921399
Médiane du revenue    : 27834512.0
RMSE : 147895350.47091815
RMSE relatif (RMSE / std)  : 0.6328367411254376
RMSE relatif (RMSE / mean) : 1.5497389549720437

In [7]:
param_grid = {
    "n_estimators": [100],
    "max_depth": [None],
    "tfidf_max_features": [3000],
    "tfidf_ngram_range": [(1, 1), (1, 2), (2, 3)],
    "tfidf_min_df": [2, 5],
}

In [8]:
results = mod.grid_search_random_forest(df_train, param_grid=param_grid)
results

6 combinations to test...
RMSE: 154,398,432 (+/- 144,366,209) | {'n_estimators': 100, 'max_depth': None, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 214,131,961 (+/- 150,125,838) | {'n_estimators': 100, 'max_depth': None, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 158,440,675 (+/- 142,840,650) | {'n_estimators': 100, 'max_depth': None, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 214,965,455 (+/- 152,142,482) | {'n_estimators': 100, 'max_depth': None, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 162,743,306 (+/- 136,601,695) | {'n_estimators': 100, 'max_depth': None, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (2, 3), 'tfidf_min_df': 2}
RMSE: nan (+/- nan) | {'n_estimators': 100, 'max_depth': None, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (2, 3), 'tfidf_min_df': 5}

/opt/python/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:490: FitFailedWarning:
4 fits failed out of a total of 10.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/python/lib/python3.13/site-packages/sklearn/model_selection/_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.13/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/python/lib/python3.13/site-packages/sklearn/pipeline.py", line 613, in fit
    Xt = self._fit(X, y, routed_params, raw_params=params)
  File "/opt/python/lib/python3.13/site-packages/sklearn/pipeline.py", line 547, in _fit
    X, fitted_transformer = fit_transform_one_cached(
                            ~~~~~~~~~~~~~~~~~~~~~~~~^
        cloned_transformer,
        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        params=step_params,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/python/lib/python3.13/site-packages/joblib/memory.py", line 326, in __call__
    return self.func(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.13/site-packages/sklearn/pipeline.py", line 1484, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/python/lib/python3.13/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/python/lib/python3.13/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/python/lib/python3.13/site-packages/sklearn/compose/_column_transformer.py", line 999, in fit_transform
    result = self._call_func_on_transformers(
        X,
    ...<3 lines>...
        routed_params=routed_params,
    )
  File "/opt/python/lib/python3.13/site-packages/sklearn/compose/_column_transformer.py", line 901, in _call_func_on_transformers
    return Parallel(n_jobs=self.n_jobs)(jobs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/opt/python/lib/python3.13/site-packages/sklearn/utils/parallel.py", line 91, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.13/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
                                                ~~~~^^^^^^^^
  File "/opt/python/lib/python3.13/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/opt/python/lib/python3.13/site-packages/sklearn/utils/parallel.py", line 184, in __call__
    return self.function(*args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.13/site-packages/sklearn/pipeline.py", line 1484, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/python/lib/python3.13/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/python/lib/python3.13/site-packages/sklearn/pipeline.py", line 689, in fit_transform
    return last_step.fit_transform(
           ~~~~~~~~~~~~~~~~~~~~~~~^
        Xt, y, **last_step_params["fit_transform"]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/python/lib/python3.13/site-packages/sklearn/feature_extraction/text.py", line 2104, in fit_transform
    X = super().fit_transform(raw_documents)
  File "/opt/python/lib/python3.13/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/python/lib/python3.13/site-packages/sklearn/feature_extraction/text.py", line 1399, in fit_transform
    X = self._limit_features(
        X, vocabulary, max_doc_count, min_doc_count, max_features
    )
  File "/opt/python/lib/python3.13/site-packages/sklearn/feature_extraction/text.py", line 1251, in _limit_features
    raise ValueError(
        "After pruning, no terms remain. Try a lower min_df or a higher max_df."
    )
ValueError: After pruning, no terms remain. Try a lower min_df or a higher max_df.

  warnings.warn(some_fits_failed_message, FitFailedWarning)

,n_estimators,max_depth,tfidf_max_features,tfidf_ngram_range,tfidf_min_df,rmse_mean,rmse_std
0,100,None,3000,"(1, 1)",2,1.543984e+08,1.443662e+08
2,100,None,3000,"(1, 2)",2,1.584407e+08,1.428406e+08
4,100,None,3000,"(2, 3)",2,1.627433e+08,1.366017e+08
1,100,None,3000,"(1, 1)",5,2.141320e+08,1.501258e+08
3,100,None,3000,"(1, 2)",5,2.149655e+08,1.521425e+08
5,100,None,3000,"(2, 3)",5,NaN,NaN

In [9]:
results = mod.grid_search_elastic_net(df_train)

576 combinations to test...
RMSE: 179,911,342 (+/- 120,999,972) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 181,315,478 (+/- 123,192,386) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 201,857,717 (+/- 104,395,917) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 178,987,592 (+/- 122,715,764) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 181,758,435 (+/- 123,331,031) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 201,798,740 (+/- 104,358,534) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 179,161,051 (+/- 120,709,138) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 181,315,478 (+/- 123,192,386) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 201,857,717 (+/- 104,395,917) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 179,931,349 (+/- 120,661,288) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 181,758,435 (+/- 123,331,031) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 201,798,740 (+/- 104,358,534) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 179,161,051 (+/- 120,709,138) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 181,315,478 (+/- 123,192,386) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 201,857,717 (+/- 104,395,917) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 179,484,685 (+/- 120,245,258) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 181,758,435 (+/- 123,331,031) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 201,798,740 (+/- 104,358,534) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 179,161,051 (+/- 120,709,138) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 181,315,478 (+/- 123,192,386) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 201,857,717 (+/- 104,395,917) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 179,484,685 (+/- 120,245,258) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 181,758,435 (+/- 123,331,031) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 201,798,740 (+/- 104,358,534) | {'alpha': 0.01, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 181,267,914 (+/- 121,213,085) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 183,309,105 (+/- 123,298,490) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 208,378,387 (+/- 103,222,187) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 180,221,065 (+/- 123,148,195) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 183,795,078 (+/- 123,466,224) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 208,308,384 (+/- 103,193,211) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 180,374,338 (+/- 120,952,890) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 183,309,105 (+/- 123,298,490) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 208,378,387 (+/- 103,222,187) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 181,196,409 (+/- 120,928,528) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 183,795,078 (+/- 123,466,224) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 208,308,384 (+/- 103,193,211) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 180,374,338 (+/- 120,952,890) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 183,309,105 (+/- 123,298,490) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 208,378,387 (+/- 103,222,187) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 180,687,427 (+/- 120,479,592) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 183,795,078 (+/- 123,466,224) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 208,308,384 (+/- 103,193,211) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 180,374,338 (+/- 120,952,890) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 183,309,105 (+/- 123,298,490) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 208,378,387 (+/- 103,222,187) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 180,687,427 (+/- 120,479,592) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 183,795,078 (+/- 123,466,224) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 208,308,384 (+/- 103,193,211) | {'alpha': 0.01, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 182,905,918 (+/- 121,436,555) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 186,002,556 (+/- 123,192,213) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 217,945,630 (+/- 101,749,890) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 181,714,811 (+/- 123,645,395) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 186,539,028 (+/- 123,410,555) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 217,859,385 (+/- 101,744,465) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 181,810,120 (+/- 121,237,932) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 186,002,556 (+/- 123,192,213) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 217,945,630 (+/- 101,749,890) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 182,689,237 (+/- 121,251,404) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 186,539,028 (+/- 123,410,555) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 217,859,385 (+/- 101,744,465) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 181,810,120 (+/- 121,237,932) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 186,002,556 (+/- 123,192,213) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 217,945,630 (+/- 101,749,890) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 182,095,471 (+/- 120,766,755) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 186,539,028 (+/- 123,410,555) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 217,859,385 (+/- 101,744,465) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 181,810,120 (+/- 121,237,932) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 186,002,556 (+/- 123,192,213) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 217,945,630 (+/- 101,749,890) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 182,095,471 (+/- 120,766,755) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 186,539,028 (+/- 123,410,555) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 217,859,385 (+/- 101,744,465) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 184,955,896 (+/- 121,644,654) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 189,930,501 (+/- 122,619,210) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 234,132,007 (+/- 99,717,355) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 183,605,998 (+/- 124,194,798) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 190,530,747 (+/- 122,927,791) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 234,009,474 (+/- 99,782,055) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 183,557,533 (+/- 121,567,277) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 189,930,501 (+/- 122,619,210) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 234,132,007 (+/- 99,717,355) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 184,496,663 (+/- 121,644,433) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 190,530,747 (+/- 122,927,791) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 234,009,474 (+/- 99,782,055) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 183,557,533 (+/- 121,567,277) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 189,930,501 (+/- 122,619,210) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 234,132,007 (+/- 99,717,355) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 183,781,123 (+/- 121,123,096) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 190,530,747 (+/- 122,927,791) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 234,009,474 (+/- 99,782,055) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 183,557,533 (+/- 121,567,277) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 189,930,501 (+/- 122,619,210) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 234,132,007 (+/- 99,717,355) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 183,781,123 (+/- 121,123,096) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 190,530,747 (+/- 122,927,791) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 234,009,474 (+/- 99,782,055) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 187,667,697 (+/- 121,761,408) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 196,436,988 (+/- 120,970,076) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 273,443,467 (+/- 96,814,182) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 186,180,272 (+/- 124,722,661) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 197,135,925 (+/- 121,445,218) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 273,045,653 (+/- 97,105,666) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 185,777,685 (+/- 121,931,965) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 196,436,988 (+/- 120,970,076) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 273,443,467 (+/- 96,814,182) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 186,770,240 (+/- 122,124,123) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 197,135,925 (+/- 121,445,218) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 273,045,653 (+/- 97,105,666) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 185,777,685 (+/- 121,931,965) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 196,436,988 (+/- 120,970,076) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 273,443,467 (+/- 96,814,182) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 185,866,275 (+/- 121,571,382) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 197,135,925 (+/- 121,445,218) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 273,045,653 (+/- 97,105,666) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 185,777,685 (+/- 121,931,965) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 196,436,988 (+/- 120,970,076) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 273,443,467 (+/- 96,814,182) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 185,866,275 (+/- 121,571,382) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 197,135,925 (+/- 121,445,218) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 273,045,653 (+/- 97,105,666) | {'alpha': 0.01, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 274,122,312 (+/- 159,474,029) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 312,977,609 (+/- 161,666,175) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 360,844,453 (+/- 105,456,560) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.310e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.681e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.607e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.396e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.421e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.960e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.442e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 290,900,414 (+/- 201,088,684) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 310,988,612 (+/- 170,979,787) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 357,759,549 (+/- 104,809,673) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.380e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.952e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.390e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.421e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 283,819,292 (+/- 279,084,663) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 312,977,609 (+/- 161,666,175) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 360,844,453 (+/- 105,456,560) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.310e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.607e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.442e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.681e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.396e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.421e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.960e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 294,268,151 (+/- 284,253,560) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 310,988,612 (+/- 170,979,787) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 357,759,549 (+/- 104,809,673) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.380e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.421e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.952e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.390e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 283,819,292 (+/- 279,084,663) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 312,977,609 (+/- 161,666,175) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 360,844,453 (+/- 105,456,560) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.310e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.421e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.396e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.442e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.607e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.681e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.960e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 302,605,854 (+/- 315,401,282) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 310,988,612 (+/- 170,979,787) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 357,759,549 (+/- 104,809,673) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.380e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.952e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.390e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.421e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 283,819,292 (+/- 279,084,663) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 312,977,609 (+/- 161,666,175) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 360,844,453 (+/- 105,456,560) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.310e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.396e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.421e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.960e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.607e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.681e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.442e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 302,605,854 (+/- 315,401,282) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 310,988,612 (+/- 170,979,787) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.952e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.380e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.421e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.390e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 357,759,549 (+/- 104,809,673) | {'alpha': 0.01, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 166,313,146 (+/- 119,588,533) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 166,329,538 (+/- 120,060,136) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 167,061,895 (+/- 116,230,309) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 166,209,224 (+/- 119,875,781) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 166,415,294 (+/- 120,096,042) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 167,056,725 (+/- 116,223,942) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 166,236,166 (+/- 119,488,662) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 166,329,538 (+/- 120,060,136) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 167,061,895 (+/- 116,230,309) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 166,454,596 (+/- 119,434,368) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 166,415,294 (+/- 120,096,042) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 167,056,725 (+/- 116,223,942) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 166,236,166 (+/- 119,488,662) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 166,329,538 (+/- 120,060,136) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 167,061,895 (+/- 116,230,309) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 166,369,802 (+/- 119,363,017) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 166,415,294 (+/- 120,096,042) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 167,056,725 (+/- 116,223,942) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 166,236,166 (+/- 119,488,662) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 166,329,538 (+/- 120,060,136) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 167,061,895 (+/- 116,230,309) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 166,369,802 (+/- 119,363,017) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 166,415,294 (+/- 120,096,042) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 167,056,725 (+/- 116,223,942) | {'alpha': 0.1, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 167,672,616 (+/- 119,469,017) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 167,696,393 (+/- 120,096,791) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 169,061,529 (+/- 115,133,070) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 167,532,564 (+/- 119,834,630) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 167,804,400 (+/- 120,140,690) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 169,054,398 (+/- 115,123,640) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 167,567,280 (+/- 119,339,739) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 167,696,393 (+/- 120,096,791) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 169,061,529 (+/- 115,133,070) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 167,830,996 (+/- 119,277,591) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 167,804,400 (+/- 120,140,690) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 169,054,398 (+/- 115,123,640) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 167,567,280 (+/- 119,339,739) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 167,696,393 (+/- 120,096,791) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 169,061,529 (+/- 115,133,070) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 167,725,160 (+/- 119,180,840) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 167,804,400 (+/- 120,140,690) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 169,054,398 (+/- 115,123,640) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 167,567,280 (+/- 119,339,739) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 167,696,393 (+/- 120,096,791) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 169,061,529 (+/- 115,133,070) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 167,725,160 (+/- 119,180,840) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 167,804,400 (+/- 120,140,690) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 169,054,398 (+/- 115,123,640) | {'alpha': 0.1, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 169,545,826 (+/- 119,478,331) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 169,584,919 (+/- 120,368,054) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 172,213,207 (+/- 113,539,928) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 169,339,305 (+/- 119,975,472) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 169,729,667 (+/- 120,424,100) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 172,202,541 (+/- 113,525,093) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 169,391,116 (+/- 119,304,412) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 169,584,919 (+/- 120,368,054) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 172,213,207 (+/- 113,539,928) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 169,725,406 (+/- 119,231,719) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 169,729,667 (+/- 120,424,100) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 172,202,541 (+/- 113,525,093) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 169,391,116 (+/- 119,304,412) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 169,584,919 (+/- 120,368,054) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 172,213,207 (+/- 113,539,928) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 169,585,478 (+/- 119,093,426) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 169,729,667 (+/- 120,424,100) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 172,202,541 (+/- 113,525,093) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 169,391,116 (+/- 119,304,412) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 169,584,919 (+/- 120,368,054) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 172,213,207 (+/- 113,539,928) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 169,585,478 (+/- 119,093,426) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 169,729,667 (+/- 120,424,100) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 172,202,541 (+/- 113,525,093) | {'alpha': 0.1, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 172,575,950 (+/- 119,775,204) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 172,689,056 (+/- 121,161,606) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 178,434,725 (+/- 110,843,448) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 172,218,987 (+/- 120,540,555) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 172,906,615 (+/- 121,237,011) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 178,415,728 (+/- 110,818,045) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 172,313,315 (+/- 119,530,506) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 172,689,056 (+/- 121,161,606) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 178,434,725 (+/- 110,843,448) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 172,773,236 (+/- 119,445,758) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 172,906,615 (+/- 121,237,011) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 178,415,728 (+/- 110,818,045) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 172,313,315 (+/- 119,530,506) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 172,689,056 (+/- 121,161,606) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 178,434,725 (+/- 110,843,448) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 172,566,748 (+/- 119,229,586) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 172,906,615 (+/- 121,237,011) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 178,415,728 (+/- 110,818,045) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 172,313,315 (+/- 119,530,506) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 172,689,056 (+/- 121,161,606) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 178,434,725 (+/- 110,843,448) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 172,566,748 (+/- 119,229,586) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 172,906,615 (+/- 121,237,011) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 178,415,728 (+/- 110,818,045) | {'alpha': 0.1, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 179,313,354 (+/- 120,900,220) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 180,493,521 (+/- 123,099,892) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 199,288,981 (+/- 104,909,043) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 178,443,540 (+/- 122,522,704) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 180,917,184 (+/- 123,228,774) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 199,234,456 (+/- 104,869,947) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 178,619,828 (+/- 120,601,024) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 180,493,521 (+/- 123,099,892) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 199,288,981 (+/- 104,909,043) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 179,366,301 (+/- 120,544,867) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 180,917,184 (+/- 123,228,774) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 199,234,456 (+/- 104,869,947) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 178,619,828 (+/- 120,601,024) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 180,493,521 (+/- 123,099,892) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 199,288,981 (+/- 104,909,043) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 178,944,984 (+/- 120,144,096) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 180,917,184 (+/- 123,228,774) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 199,234,456 (+/- 104,869,947) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 178,619,828 (+/- 120,601,024) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 180,493,521 (+/- 123,099,892) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 199,288,981 (+/- 104,909,043) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 178,944,984 (+/- 120,144,096) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 180,917,184 (+/- 123,228,774) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 199,234,456 (+/- 104,869,947) | {'alpha': 0.1, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 274,122,245 (+/- 159,474,056) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 312,977,510 (+/- 161,666,211) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.310e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.396e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.421e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.607e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.681e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.442e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.960e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 360,844,391 (+/- 105,456,594) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 290,900,306 (+/- 201,088,788) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 310,988,502 (+/- 170,979,820) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.379e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.389e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.421e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.952e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 357,759,485 (+/- 104,809,704) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 283,819,243 (+/- 279,084,655) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 312,977,510 (+/- 161,666,211) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.310e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.681e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.442e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.421e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.607e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.396e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.960e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 360,844,391 (+/- 105,456,594) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 294,268,107 (+/- 284,253,613) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 310,988,502 (+/- 170,979,820) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.389e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.421e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.379e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.952e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 357,759,485 (+/- 104,809,704) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 283,819,243 (+/- 279,084,655) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 312,977,510 (+/- 161,666,211) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.310e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.421e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.607e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.960e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.396e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.681e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.442e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 360,844,391 (+/- 105,456,594) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 302,605,736 (+/- 315,401,345) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 310,988,502 (+/- 170,979,820) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.952e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.421e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.379e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.389e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 357,759,485 (+/- 104,809,704) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 283,819,243 (+/- 279,084,655) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 312,977,510 (+/- 161,666,211) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.396e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.421e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.310e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.681e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.442e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.607e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.960e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 360,844,391 (+/- 105,456,594) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 302,605,736 (+/- 315,401,345) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 310,988,502 (+/- 170,979,820) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.389e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.379e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.421e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.952e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 357,759,485 (+/- 104,809,704) | {'alpha': 0.1, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 150,469,654 (+/- 130,806,071) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 150,443,858 (+/- 130,814,245) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 150,287,159 (+/- 130,571,150) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 150,452,786 (+/- 130,830,112) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 150,447,199 (+/- 130,821,406) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 150,287,927 (+/- 130,571,034) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 150,468,047 (+/- 130,813,560) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 150,443,858 (+/- 130,814,245) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 150,287,159 (+/- 130,571,150) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 150,498,228 (+/- 130,801,231) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 150,447,199 (+/- 130,821,406) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 150,287,927 (+/- 130,571,034) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 150,468,047 (+/- 130,813,560) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 150,443,858 (+/- 130,814,245) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 150,287,159 (+/- 130,571,150) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 150,489,733 (+/- 130,807,920) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 150,447,199 (+/- 130,821,406) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 150,287,927 (+/- 130,571,034) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 150,468,047 (+/- 130,813,560) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 150,443,858 (+/- 130,814,245) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 150,287,159 (+/- 130,571,150) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 150,489,733 (+/- 130,807,920) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 150,447,199 (+/- 130,821,406) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 150,287,927 (+/- 130,571,034) | {'alpha': 1.0, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 152,463,735 (+/- 128,302,039) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 152,438,526 (+/- 128,318,492) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 152,245,248 (+/- 127,989,621) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 152,446,449 (+/- 128,333,104) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 152,444,783 (+/- 128,326,723) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 152,245,857 (+/- 127,989,554) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 152,462,205 (+/- 128,307,190) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 152,438,526 (+/- 128,318,492) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 152,245,248 (+/- 127,989,621) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 152,500,475 (+/- 128,292,389) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 152,444,783 (+/- 128,326,723) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 152,245,857 (+/- 127,989,554) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 152,462,205 (+/- 128,307,190) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 152,438,526 (+/- 128,318,492) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 152,245,248 (+/- 127,989,621) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 152,489,668 (+/- 128,298,225) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 152,444,783 (+/- 128,326,723) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 152,245,857 (+/- 127,989,554) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 152,462,205 (+/- 128,307,190) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 152,438,526 (+/- 128,318,492) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 152,245,248 (+/- 127,989,621) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 152,489,668 (+/- 128,298,225) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 152,444,783 (+/- 128,326,723) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 152,245,857 (+/- 127,989,554) | {'alpha': 1.0, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 155,194,991 (+/- 125,516,561) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 155,172,120 (+/- 125,551,430) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 154,935,075 (+/- 125,055,285) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 155,175,987 (+/- 125,561,226) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 155,183,696 (+/- 125,561,362) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 154,935,384 (+/- 125,055,216) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 155,192,278 (+/- 125,516,380) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 155,172,120 (+/- 125,551,430) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 154,935,075 (+/- 125,055,285) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 155,244,313 (+/- 125,497,692) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 155,183,696 (+/- 125,561,362) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 154,935,384 (+/- 125,055,216) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 155,192,278 (+/- 125,516,380) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 155,172,120 (+/- 125,551,430) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 154,935,075 (+/- 125,055,285) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 155,229,206 (+/- 125,500,851) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 155,183,696 (+/- 125,561,362) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 154,935,384 (+/- 125,055,216) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 155,192,278 (+/- 125,516,380) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 155,172,120 (+/- 125,551,430) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 154,935,075 (+/- 125,055,285) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 155,229,206 (+/- 125,500,851) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 155,183,696 (+/- 125,561,362) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 154,935,384 (+/- 125,055,216) | {'alpha': 1.0, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 159,081,396 (+/- 122,491,147) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 159,066,112 (+/- 122,579,393) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 158,812,522 (+/- 121,645,908) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 159,054,586 (+/- 122,570,606) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 159,089,807 (+/- 122,593,105) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 158,812,095 (+/- 121,645,506) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 159,071,671 (+/- 122,476,405) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 159,066,112 (+/- 122,579,393) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 158,812,522 (+/- 121,645,908) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 159,153,127 (+/- 122,450,301) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 159,089,807 (+/- 122,593,105) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 158,812,095 (+/- 121,645,506) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 159,071,671 (+/- 122,476,405) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 159,066,112 (+/- 122,579,393) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 158,812,522 (+/- 121,645,908) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 159,127,468 (+/- 122,444,426) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 159,089,807 (+/- 122,593,105) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 158,812,095 (+/- 121,645,506) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 159,071,671 (+/- 122,476,405) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 159,066,112 (+/- 122,579,393) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 158,812,522 (+/- 121,645,908) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 159,127,468 (+/- 122,444,426) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 159,089,807 (+/- 122,593,105) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 158,812,095 (+/- 121,645,506) | {'alpha': 1.0, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 165,744,724 (+/- 119,676,303) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 165,758,210 (+/- 120,092,033) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 166,288,649 (+/- 116,673,128) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 165,653,119 (+/- 119,935,149) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 165,835,815 (+/- 120,124,940) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 166,284,165 (+/- 116,667,806) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 165,677,793 (+/- 119,587,545) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 165,758,210 (+/- 120,092,033) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 166,288,649 (+/- 116,673,128) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 165,879,148 (+/- 119,536,403) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 165,835,815 (+/- 120,124,940) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 166,284,165 (+/- 116,667,806) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 165,677,793 (+/- 119,587,545) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 165,758,210 (+/- 120,092,033) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 166,288,649 (+/- 116,673,128) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 165,802,138 (+/- 119,474,299) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 165,835,815 (+/- 120,124,940) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 166,284,165 (+/- 116,667,806) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 165,677,793 (+/- 119,587,545) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 165,758,210 (+/- 120,092,033) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 166,288,649 (+/- 116,673,128) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 165,802,138 (+/- 119,474,299) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 165,835,815 (+/- 120,124,940) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 166,284,165 (+/- 116,667,806) | {'alpha': 1.0, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 274,121,575 (+/- 159,474,318) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 312,976,526 (+/- 161,666,570) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.310e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.396e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.442e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.960e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.608e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.681e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.422e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 360,843,772 (+/- 105,456,944) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 290,899,226 (+/- 201,089,823) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 310,987,402 (+/- 170,980,142) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.422e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.952e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.379e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.389e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 357,758,844 (+/- 104,810,011) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 283,819,032 (+/- 279,084,569) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 312,976,526 (+/- 161,666,570) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.396e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.310e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.422e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.960e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.442e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.681e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.608e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 360,843,772 (+/- 105,456,944) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 294,267,708 (+/- 284,254,151) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 310,987,402 (+/- 170,980,142) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.422e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.379e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.952e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.389e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 357,758,844 (+/- 104,810,011) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 283,819,032 (+/- 279,084,569) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 312,976,526 (+/- 161,666,570) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.396e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.310e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.422e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.608e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.442e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.681e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.960e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 360,843,772 (+/- 105,456,944) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 302,604,593 (+/- 315,402,111) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 310,987,402 (+/- 170,980,142) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.389e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.952e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.422e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.379e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 357,758,844 (+/- 104,810,011) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 283,819,032 (+/- 279,084,569) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 312,976,526 (+/- 161,666,570) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.310e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.396e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.422e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.960e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.608e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.681e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.442e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 360,843,772 (+/- 105,456,944) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 302,604,593 (+/- 315,402,111) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 310,987,402 (+/- 170,980,142) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.379e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.422e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.059e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.952e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.389e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 357,758,844 (+/- 104,810,011) | {'alpha': 1.0, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 154,994,295 (+/- 153,653,656) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 154,983,242 (+/- 153,653,203) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 154,988,190 (+/- 153,631,774) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 154,987,363 (+/- 153,656,033) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 154,981,569 (+/- 153,654,261) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 154,988,538 (+/- 153,631,581) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 154,993,557 (+/- 153,655,913) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 154,983,242 (+/- 153,653,203) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 154,988,190 (+/- 153,631,774) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 154,995,562 (+/- 153,654,757) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 154,981,569 (+/- 153,654,261) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 154,988,538 (+/- 153,631,581) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 154,993,557 (+/- 153,655,913) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 154,983,242 (+/- 153,653,203) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 154,988,190 (+/- 153,631,774) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 154,995,631 (+/- 153,655,862) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 154,981,569 (+/- 153,654,261) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 154,988,538 (+/- 153,631,581) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 154,993,557 (+/- 153,655,913) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 154,983,242 (+/- 153,653,203) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 154,988,190 (+/- 153,631,774) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 154,995,631 (+/- 153,655,862) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 154,981,569 (+/- 153,654,261) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 154,988,538 (+/- 153,631,581) | {'alpha': 10.0, 'l1_ratio': 0.1, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 152,368,650 (+/- 152,441,792) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 152,355,415 (+/- 152,441,241) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 152,358,119 (+/- 152,413,776) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 152,360,349 (+/- 152,444,815) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 152,353,504 (+/- 152,442,592) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 152,358,580 (+/- 152,413,535) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 152,367,640 (+/- 152,444,730) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 152,355,415 (+/- 152,441,241) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 152,358,119 (+/- 152,413,776) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 152,370,466 (+/- 152,443,113) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 152,353,504 (+/- 152,442,592) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 152,358,580 (+/- 152,413,535) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 152,367,640 (+/- 152,444,730) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 152,355,415 (+/- 152,441,241) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 152,358,119 (+/- 152,413,776) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 152,370,346 (+/- 152,444,619) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 152,353,504 (+/- 152,442,592) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 152,358,580 (+/- 152,413,535) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 152,367,640 (+/- 152,444,730) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 152,355,415 (+/- 152,441,241) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 152,358,119 (+/- 152,413,776) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 152,370,346 (+/- 152,444,619) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 152,353,504 (+/- 152,442,592) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 152,358,580 (+/- 152,413,535) | {'alpha': 10.0, 'l1_ratio': 0.3, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 149,168,657 (+/- 150,236,565) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 149,152,432 (+/- 150,235,688) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 149,148,332 (+/- 150,197,695) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 149,158,344 (+/- 150,240,791) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 149,150,274 (+/- 150,237,549) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 149,148,972 (+/- 150,197,385) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 149,167,085 (+/- 150,240,775) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 149,152,432 (+/- 150,235,688) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 149,148,332 (+/- 150,197,695) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 149,171,550 (+/- 150,238,274) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 149,150,274 (+/- 150,237,549) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 149,148,972 (+/- 150,197,385) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 149,167,085 (+/- 150,240,775) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 149,152,432 (+/- 150,235,688) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 149,148,332 (+/- 150,197,695) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 149,170,897 (+/- 150,240,588) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 149,150,274 (+/- 150,237,549) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 149,148,972 (+/- 150,197,385) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 149,167,085 (+/- 150,240,775) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 149,152,432 (+/- 150,235,688) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 149,148,332 (+/- 150,197,695) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 149,170,897 (+/- 150,240,588) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 149,150,274 (+/- 150,237,549) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 149,148,972 (+/- 150,197,385) | {'alpha': 10.0, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 146,189,316 (+/- 145,372,778) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 146,168,964 (+/- 145,371,150) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 146,141,841 (+/- 145,308,513) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 146,175,834 (+/- 145,380,040) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 146,166,822 (+/- 145,374,130) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 146,142,733 (+/- 145,308,140) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 146,186,711 (+/- 145,379,533) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 146,168,964 (+/- 145,371,150) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 146,141,841 (+/- 145,308,513) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 146,195,218 (+/- 145,375,066) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 146,166,822 (+/- 145,374,130) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 146,142,733 (+/- 145,308,140) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 146,186,711 (+/- 145,379,533) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 146,168,964 (+/- 145,371,150) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 146,141,841 (+/- 145,308,513) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 146,193,037 (+/- 145,379,186) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 146,166,822 (+/- 145,374,130) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 146,142,733 (+/- 145,308,140) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 146,186,711 (+/- 145,379,533) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 146,168,964 (+/- 145,371,150) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 146,141,841 (+/- 145,308,513) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 146,193,037 (+/- 145,379,186) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 146,166,822 (+/- 145,374,130) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 146,142,733 (+/- 145,308,140) | {'alpha': 10.0, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 149,678,063 (+/- 131,956,135) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 149,652,271 (+/- 131,961,852) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 149,510,659 (+/- 131,747,394) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 149,661,281 (+/- 131,977,804) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 149,654,621 (+/- 131,968,592) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 149,511,480 (+/- 131,747,250) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 149,676,293 (+/- 131,964,257) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 149,652,271 (+/- 131,961,852) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 149,510,659 (+/- 131,747,394) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 149,703,551 (+/- 131,952,865) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 149,654,621 (+/- 131,968,592) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 149,511,480 (+/- 131,747,250) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 149,676,293 (+/- 131,964,257) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 149,652,271 (+/- 131,961,852) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 149,510,659 (+/- 131,747,394) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 149,695,858 (+/- 131,959,689) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 149,654,621 (+/- 131,968,592) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 149,511,480 (+/- 131,747,250) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 149,676,293 (+/- 131,964,257) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 149,652,271 (+/- 131,961,852) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}
RMSE: 149,510,659 (+/- 131,747,394) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 149,695,858 (+/- 131,959,689) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 149,654,621 (+/- 131,968,592) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 149,511,480 (+/- 131,747,250) | {'alpha': 10.0, 'l1_ratio': 0.9, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 274,114,824 (+/- 159,476,554) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 312,966,659 (+/- 161,670,106) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.311e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.396e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.608e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.442e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.422e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.682e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.060e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.964e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 360,837,609 (+/- 105,460,466) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 290,888,175 (+/- 201,100,401) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 310,976,404 (+/- 170,983,351) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.379e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.422e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.060e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.956e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.390e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 357,752,463 (+/- 104,813,107) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 1000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 283,816,921 (+/- 279,086,168) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 312,966,659 (+/- 161,670,106) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.396e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.311e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.682e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.060e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.422e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.608e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.964e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.442e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 360,837,609 (+/- 105,460,466) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 294,264,339 (+/- 284,261,713) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 310,976,404 (+/- 170,983,351) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.379e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.390e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.060e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.422e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.956e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 357,752,463 (+/- 104,813,107) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 3000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 283,816,921 (+/- 279,086,168) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 312,966,659 (+/- 161,670,106) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.422e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.311e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.396e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.608e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.682e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.442e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.060e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.964e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 360,837,609 (+/- 105,460,466) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 302,593,833 (+/- 315,403,339) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 310,976,404 (+/- 170,983,351) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.422e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.379e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.956e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.390e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.060e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 357,752,463 (+/- 104,813,107) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}
RMSE: 283,816,921 (+/- 279,086,168) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 1}
RMSE: 312,966,659 (+/- 161,670,106) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.311e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.396e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.422e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.682e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.060e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.608e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.442e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.964e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(

RMSE: 360,837,609 (+/- 105,460,466) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5}
RMSE: 302,593,833 (+/- 315,403,339) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 1}
RMSE: 310,976,404 (+/- 170,983,351) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2}
RMSE: 357,752,463 (+/- 104,813,107) | {'alpha': 10.0, 'l1_ratio': 1.0, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5}

/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.379e+16, tolerance: 6.291e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.422e+16, tolerance: 4.218e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.390e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+16, tolerance: 6.114e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e+16, tolerance: 6.250e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e+16, tolerance: 6.252e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+16, tolerance: 6.165e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.202e+17, tolerance: 6.255e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.060e+16, tolerance: 6.253e+14
  model = cd_fast.sparse_enet_coordinate_descent(
/opt/python/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.956e+15, tolerance: 2.895e+14
  model = cd_fast.sparse_enet_coordinate_descent(

In [10]:
results.sort_values("rmse_mean")

,alpha,l1_ratio,tfidf_max_features,tfidf_ngram_range,tfidf_min_df,rmse_mean,rmse_std
512,10.00,0.7,3000,"(1, 1)",5,1.461418e+08,1.453085e+08
518,10.00,0.7,5000,"(1, 1)",5,1.461418e+08,1.453085e+08
524,10.00,0.7,10000,"(1, 1)",5,1.461418e+08,1.453085e+08
506,10.00,0.7,1000,"(1, 1)",5,1.461418e+08,1.453085e+08
521,10.00,0.7,5000,"(1, 2)",5,1.461427e+08,1.453081e+08
...,...,...,...,...,...,...,...
266,0.10,1.0,1000,"(1, 1)",5,3.608444e+08,1.054566e+08
140,0.01,1.0,10000,"(1, 1)",5,3.608445e+08,1.054566e+08
128,0.01,1.0,3000,"(1, 1)",5,3.608445e+08,1.054566e+08
122,0.01,1.0,1000,"(1, 1)",5,3.608445e+08,1.054566e+08
134,0.01,1.0,5000,"(1, 1)",5,3.608445e+08,1.054566e+08

In [81]:
param_grid = {
    "alpha": [0.01, 0.1, 1.0],
    "l1_ratio": [0.5, 0.7, 0.9],
    "tfidf_max_features": [5000, 10000],
    "tfidf_ngram_range": [(1, 1), (1, 2)],
    "tfidf_min_df": [2, 5, 10, 20, 30],
    "tfidf_max_df": [0.6, 0.8, 0.9],
}

In [82]:
results_new = mod.grid_search_elastic_net(df_train, param_grid)

540 combinaisons à tester...
RMSE: 146,919,867 (+/- 59,773,628) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.6}
RMSE: 146,919,867 (+/- 59,773,628) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.8}
RMSE: 146,919,867 (+/- 59,773,628) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.9}
RMSE: 148,003,460 (+/- 58,291,009) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.6}
RMSE: 148,003,460 (+/- 58,291,009) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.8}
RMSE: 148,003,460 (+/- 58,291,009) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.9}
RMSE: 151,414,741 (+/- 57,886,255) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.6}
RMSE: 151,414,741 (+/- 57,886,255) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.8}
RMSE: 151,414,741 (+/- 57,886,255) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.9}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.6}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.8}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.9}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.6}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.8}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.9}
RMSE: 146,642,644 (+/- 59,977,116) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.6}
RMSE: 146,642,644 (+/- 59,977,116) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.8}
RMSE: 146,642,644 (+/- 59,977,116) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.9}
RMSE: 147,748,339 (+/- 58,442,340) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.6}
RMSE: 147,748,339 (+/- 58,442,340) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.8}
RMSE: 147,748,339 (+/- 58,442,340) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.9}
RMSE: 151,306,112 (+/- 57,913,040) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.6}
RMSE: 151,306,112 (+/- 57,913,040) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.8}
RMSE: 151,306,112 (+/- 57,913,040) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.9}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.6}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.8}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.9}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.6}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.8}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.9}
RMSE: 146,919,867 (+/- 59,773,628) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.6}
RMSE: 146,919,867 (+/- 59,773,628) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.8}
RMSE: 146,919,867 (+/- 59,773,628) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.9}
RMSE: 148,003,460 (+/- 58,291,009) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.6}
RMSE: 148,003,460 (+/- 58,291,009) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.8}
RMSE: 148,003,460 (+/- 58,291,009) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.9}
RMSE: 151,414,741 (+/- 57,886,255) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.6}
RMSE: 151,414,741 (+/- 57,886,255) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.8}
RMSE: 151,414,741 (+/- 57,886,255) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.9}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.6}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.8}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.9}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.6}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.8}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.9}
RMSE: 146,642,644 (+/- 59,977,116) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.6}
RMSE: 146,642,644 (+/- 59,977,116) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.8}
RMSE: 146,642,644 (+/- 59,977,116) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.9}
RMSE: 147,748,339 (+/- 58,442,340) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.6}
RMSE: 147,748,339 (+/- 58,442,340) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.8}
RMSE: 147,748,339 (+/- 58,442,340) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.9}
RMSE: 151,306,112 (+/- 57,913,040) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.6}
RMSE: 151,306,112 (+/- 57,913,040) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.8}
RMSE: 151,306,112 (+/- 57,913,040) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.9}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.6}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.8}
RMSE: 146,023,824 (+/- 57,707,962) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.9}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.6}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.8}
RMSE: 147,174,273 (+/- 58,765,738) | {'alpha': 0.01, 'l1_ratio': 0.5, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.9}
RMSE: 148,775,942 (+/- 58,537,049) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.6}
RMSE: 148,775,942 (+/- 58,537,049) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.8}
RMSE: 148,775,942 (+/- 58,537,049) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.9}
RMSE: 151,630,442 (+/- 56,204,430) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.6}
RMSE: 151,630,442 (+/- 56,204,430) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.8}
RMSE: 151,630,442 (+/- 56,204,430) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.9}
RMSE: 156,459,033 (+/- 55,934,131) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.6}
RMSE: 156,459,033 (+/- 55,934,131) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.8}
RMSE: 156,459,033 (+/- 55,934,131) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.9}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.6}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.8}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.9}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.6}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.8}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.9}
RMSE: 148,290,945 (+/- 58,845,368) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.6}
RMSE: 148,290,945 (+/- 58,845,368) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.8}
RMSE: 148,290,945 (+/- 58,845,368) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.9}
RMSE: 151,263,213 (+/- 56,443,111) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.6}
RMSE: 151,263,213 (+/- 56,443,111) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.8}
RMSE: 151,263,213 (+/- 56,443,111) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.9}
RMSE: 156,342,755 (+/- 55,966,797) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.6}
RMSE: 156,342,755 (+/- 55,966,797) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.8}
RMSE: 156,342,755 (+/- 55,966,797) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.9}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.6}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.8}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.9}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.6}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.8}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.9}
RMSE: 148,775,942 (+/- 58,537,049) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.6}
RMSE: 148,775,942 (+/- 58,537,049) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.8}
RMSE: 148,775,942 (+/- 58,537,049) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 2, 'tfidf_max_df': 0.9}
RMSE: 151,630,442 (+/- 56,204,430) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.6}
RMSE: 151,630,442 (+/- 56,204,430) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.8}
RMSE: 151,630,442 (+/- 56,204,430) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 5, 'tfidf_max_df': 0.9}
RMSE: 156,459,033 (+/- 55,934,131) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.6}
RMSE: 156,459,033 (+/- 55,934,131) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.8}
RMSE: 156,459,033 (+/- 55,934,131) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 10, 'tfidf_max_df': 0.9}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.6}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.8}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 20, 'tfidf_max_df': 0.9}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.6}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.8}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 1), 'tfidf_min_df': 30, 'tfidf_max_df': 0.9}
RMSE: 148,290,945 (+/- 58,845,368) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.6}
RMSE: 148,290,945 (+/- 58,845,368) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.8}
RMSE: 148,290,945 (+/- 58,845,368) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 2, 'tfidf_max_df': 0.9}
RMSE: 151,263,213 (+/- 56,443,111) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.6}
RMSE: 151,263,213 (+/- 56,443,111) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.8}
RMSE: 151,263,213 (+/- 56,443,111) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 5, 'tfidf_max_df': 0.9}
RMSE: 156,342,755 (+/- 55,966,797) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.6}
RMSE: 156,342,755 (+/- 55,966,797) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.8}
RMSE: 156,342,755 (+/- 55,966,797) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 10, 'tfidf_max_df': 0.9}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.6}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.8}
RMSE: 147,720,226 (+/- 56,519,517) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 20, 'tfidf_max_df': 0.9}
RMSE: 148,247,175 (+/- 58,011,856) | {'alpha': 0.01, 'l1_ratio': 0.7, 'tfidf_max_features': 10000, 'tfidf_ngram_range': (1, 2), 'tfidf_min_df': 30, 'tfidf_max_df': 0.6}

In [83]:
results_new.sort_values(["rmse_mean"]).head(20)

,alpha,l1_ratio,tfidf_max_features,tfidf_ngram_range,tfidf_min_df,tfidf_max_df,rmse_mean,rmse_std
266,0.1,0.7,5000,"(1, 2)",20,0.9,1.428925e+08,6.302261e+07
264,0.1,0.7,5000,"(1, 2)",20,0.6,1.428925e+08,6.302261e+07
265,0.1,0.7,5000,"(1, 2)",20,0.8,1.428925e+08,6.302261e+07
250,0.1,0.7,5000,"(1, 1)",20,0.8,1.428925e+08,6.302261e+07
251,0.1,0.7,5000,"(1, 1)",20,0.9,1.428925e+08,6.302261e+07
249,0.1,0.7,5000,"(1, 1)",20,0.6,1.428925e+08,6.302261e+07
280,0.1,0.7,10000,"(1, 1)",20,0.8,1.428925e+08,6.302261e+07
279,0.1,0.7,10000,"(1, 1)",20,0.6,1.428925e+08,6.302261e+07
281,0.1,0.7,10000,"(1, 1)",20,0.9,1.428925e+08,6.302261e+07
295,0.1,0.7,10000,"(1, 2)",20,0.8,1.428925e+08,6.302261e+07
296,0.1,0.7,10000,"(1, 2)",20,0.9,1.428925e+08,6.302261e+07
294,0.1,0.7,10000,"(1, 2)",20,0.6,1.428925e+08,6.302261e+07
205,0.1,0.5,5000,"(1, 2)",20,0.8,1.433665e+08,6.457786e+07
234,0.1,0.5,10000,"(1, 2)",20,0.6,1.433665e+08,6.457786e+07
206,0.1,0.5,5000,"(1, 2)",20,0.9,1.433665e+08,6.457786e+07
221,0.1,0.5,10000,"(1, 1)",20,0.9,1.433665e+08,6.457786e+07
220,0.1,0.5,10000,"(1, 1)",20,0.8,1.433665e+08,6.457786e+07
219,0.1,0.5,10000,"(1, 1)",20,0.6,1.433665e+08,6.457786e+07
191,0.1,0.5,5000,"(1, 1)",20,0.9,1.433665e+08,6.457786e+07
189,0.1,0.5,5000,"(1, 1)",20,0.6,1.433665e+08,6.457786e+07